logging:
  level:
    net.shyshkin: debug

spring:
  graphql:
    path: /student-service
    graphiql:
      enabled: true
      path: /app-ui
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/graphql_db
    username: graphql_user
    password: graphql_password
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true




