logging:
  level:
    net.shyshkin: debug

spring:
  graphql:
    path: /student-service
    graphiql:
      enabled: true
      path: /app-ui
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:23306/graphql_db}
    username: ${DATABASE_USERNAME:graphql_user}
    password: ${DATABASE_PASSWORD:graphql_password}
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

---
spring:
  config:
    activate:
      on-profile: testcontainer
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
  sql:
    init:
      data-locations: classpath:database-testcontainer/data.sql
      schema-locations: classpath:database-testcontainer/schema.sql

