logging:
  level:
    net.shyshkin: debug

graphiql:
  mapping: /app-ui
  endpoint: /student-service
graphql:
  servlet:
    mapping: /student-service

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/graphql_db
    username: graphql_user
    password: graphql_password
